version: "3"
services:
  api:
    image: node
    working_dir: /code
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: .
        target: /code

  db:
    image: mongo
    ports:
      - 27017:27017
